repository_research_task:
  description: "Fetch the list of files from a GitHub repository."
  expected_output: "A markdown list of key files, including ALL subdirectories EXACTLY as they are in the root directory, saved to {project_files}."
  agent: github_researcher
  output_file: output/project_files.md

github_code_interpreter_task:
  description: "Get files names listed in {project_files}. Use files names to retrieve their content from GitHub."
  expected_output: "A detailed overview of each file saved in {project_files_overview}."
  agent: github_code_interpreter
  output_file: output/project_files_overview.md
  context:
    - repository_research_task

readme_creation_task:
  description: "Generate a README.md using the project overview from {project_files_overview}."
  expected_output: "A well-structured README.md saved as 'report.md'."
  agent: documentation_writer
  output_file: output/report.md
  context:
    - github_code_interpreter_task
